config/routes.rb
Rails.application.routes.draw do
  resources :micropost

  root 'micropost#index'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  validates :title, { presence: true,
                      length: { maximum: 24} }
  validates :content, { presence: true,
                        length: { in: 20..140 } }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/micropost_controller.rb
class MicropostController < ApplicationController
  def index
    @microposts = Micropost.all.sort.reverse
  end

  def new
    @micropost = Micropost.new
  end

  def create
    @micropost = Micropost.new(micropost_params)

    if @micropost.save
      flash[:notice] = 'New micropost added!'
      redirect_to action: 'index'
    else
      flash[:notice] = 'Some kind of error happened when trying to save micropost. :('
      render action: 'new'
    end
  end

  def show
    @micropost = Micropost.find(params[:id])
  end

  def edit
    @micropost = Micropost.find(params[:id])
  end

  def update
    @micropost = Micropost.find(params[:id])

    if @micropost.update(micropost_params)
     flash[:notice] = 'Micropost edited!'
     redirect_to micropost_path(@micropost)
    else
     flash[:notice] = 'Some kind of error happened when trying to save micropost. :('
     render action: 'edit'
    end
  end

  def destroy
    @micropost = Micropost.find(params[:id])

    flash[:notice] = @micropost.destroy ? 'Micropost destroyed!' : 'Micropost still exists. :<'

    redirect_to micropost_index_path
  end

  private
  def micropost_params
    params.require(:micropost).permit([:title, :content])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ROR2Blogwithvalidations
    =stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    =javascript_include_tag 'application', 'data-turbolinks-track' => true
    =csrf_meta_tags
  %body
    =yield

app/views/micropost/_form.html.haml
= form_for @micropost do |f|
  - if @micropost.errors.any?
    %h2
      = pluralize(@micropost.errors.count, 'error')
      prohibited
      this micropost from being saved:
    %ul
      - @micropost.errors.full_messages.each do |msg|
        %li= msg

  %p
    = f.label :title
    %br/
    = f.text_field :title
  %p
    = f.label :content
    %br/
    = f.text_area :content
  %p
    = f.submit

app/views/micropost/edit.html.haml
%h1 Edit Micropost

%h4=link_to '<-- Back to listing', micropost_index_path

= form_for @micropost, url: { action: 'update' }, method: :patch do |f|
  - if @micropost.errors.any?
    %h2
      = pluralize(@micropost.errors.count, 'error')
      prohibited
      this micropost from being saved:
    %ul
      - @micropost.errors.full_messages.each do |msg|
        %li= msg

  %h2 Title:
  = f.text_field :title

  %h2 Content:
  = f.text_area :content

  %p= f.submit

app/views/micropost/index.html.haml
%h1 All microposts:

%h2=button_to 'Create one', new_micropost_path, method: :get

%table
  %tr
    %th Title
    %th Content
    %th Created
    %th
    %th
    %th

  - @microposts.each do |micropost|
    %tr
      %td= micropost.title
      %td= micropost.content
      %td= micropost.created_at
      %td= link_to 'Show', micropost
      %td= link_to 'Edit', edit_micropost_path(micropost)
      %td= link_to 'Remove', micropost_path(micropost), method: :delete, data: { confirm: 'Are you sure?' }

app/views/micropost/new.html.haml
= form_for @micropost, url: micropost_index_path, method: :post do |f|
  Title: #{f.text_field :title}
  %br
  Content: #{f.text_field :content}
  %br
  = f.submit

app/views/micropost/show.html.haml
%h2 Micropost:

%h4=link_to '<-- Back to listing', micropost_index_path

%table
  %th
    %tr
      %th Title
      %th Content
      %th
      %th
    %tr
      %td= @micropost.title
      %td= @micropost.content
      %td= link_to 'Edit', edit_micropost_path(@micropost)
      %td= link_to 'Remove', micropost_path(@micropost), method: :delete, data: { confirm: 'Are you sure?' }